# Generated by Django 2.2.1 on 2019-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='排列顺序'),
        ),
    ]
