# Generated by Django 2.2.1 on 2019-05-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeproject', '0002_auto_20190507_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-id'], 'verbose_name': '广告', 'verbose_name_plural': '广告'},
        ),
        migrations.AlterModelOptions(
            name='big_class',
            options={'verbose_name': '大类', 'verbose_name_plural': '大类'},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': '品牌', 'verbose_name_plural': '品牌'},
        ),
        migrations.AlterModelOptions(
            name='classify',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-id'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='labels',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'ordering': ['-size'], 'verbose_name': '尺寸', 'verbose_name_plural': '尺寸'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='goods',
            name='labels',
            field=models.ManyToManyField(to='storeproject.Labels', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='sex',
            field=models.BooleanField(default=0, verbose_name='男装，女装（默认）'),
        ),
    ]
