# Generated by Django 2.2.1 on 2019-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeproject', '0004_caritme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='sex',
            field=models.IntegerField(default=0, verbose_name='男装（默认），女装'),
        ),
    ]
